package com.thinkinginjava.error_handling_with_exceptions.example.chapter12_8.ex12_8_2;

/**
 * page 267
 *   -- chapter_12 通过异常处理错误
 *
 *   12.8.2 在return中使用finally
 */