package com.thinkinginjava.error_handling_with_exceptions.exercise.chapter12_5;

/**
 * page 256
 *   -- chapter_12 通过异常处理错误
 *
 *   12.5 异常说明
 */